### ISSUE TITLE
How to add images in tab

### ISSUE THREAD

**Issue by piyushgohel** [creativetimofficial/material-bootstrap-wizard#6]
Hello,

I want to add image with text in tab. is that possible?

**Comment by alexandru-paduraru** [comment]
@piyushgohel thank you for using our product. Unfortunately, images and text inside the tab will not work with the current implementation, because we get the content of each tab and place it on the "red moving box" so in this way it will always show the information from the step that you view. Here is the code that is taking care of that text: https://github.com/creativetimofficial/material-bootstrap-wizard/blob/master/assets/js/material-bootstrap-wizard.js#L129 

So you can play with it and adjust it so it will also take images.

Best,
Alex
